services:
  api_fluxo_caixa:
    build:
     context: ./fluxo-caixa-api
     dockerfile: /src/Api/Dockerfile
    ports:
     - "7550:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      pgsqlConnectionString : "Host=db;Port=5432;Database=fluxo_caixa;Username=fluxo_caixa;Password=fluxo_caixa"
    depends_on:
      - db

  consolidado_api:
    build:
     context: ./consolidado-api
     dockerfile: /src/Api/Dockerfile
    ports:
     - "7551:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      pgsqlConnectionString : "Host=db;Port=5432;Database=fluxo_caixa;Username=fluxo_caixa;Password=fluxo_caixa"
    depends_on:
      - db
  

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fluxo_caixa
      POSTGRES_USER: fluxo_caixa
      POSTGRES_PASSWORD: fluxo_caixa
    ports:
      - "6015:5432"
    volumes:
      - .docker/db_escrita_data:/var/lib/postgresql/data
      - ./entrypoint/db/:/docker-entrypoint-initdb.d/