# URL Container fluxo caixa 
@baseUrlFluxoCaixa = http://localhost:7550
@baseUrlConsolidado = http://localhost:7551

### Criar entrada
POST {{baseUrlFluxoCaixa}}/Lancamentos
Content-Type: application/json

{
  "descricao": "Entrada: Pagamento Cliente",
  "valor": 100.5,
  "tipo": 1
}

### Create a new item
POST {{baseUrlFluxoCaixa}}/Lancamentos
Content-Type: application/json

{
  "descricao": "Saida: Pagamento Fornecedor",
  "valor": 100.5,
  "tipo": 2
}

### Criar lançamento comparametros
# @prompt descricao Descrição entre 3 a 255 caracteres
# @prompt valor Valor maior que 0
# @prompt tipo 1 para entrada, 2 para saída
POST {{baseUrlFluxoCaixa}}/Lancamentos
Content-Type: application/json

{
  "descricao": "{{descricao}}",
  "valor": {{valor}},
  "tipo": {{tipo}}
}


### Get all items
GET {{baseUrlFluxoCaixa}}/Lancamentos/Listar
Accept: application/json


@dataAtual = {{dataAtual}}

### Get Relatorio Consolidado
GET {{baseUrlConsolidado}}/Diario?Data={{$localDatetime 'YYYY-MM-DD' [offset option]}}
Accept: application/pdf

